default: &default
  adapter: postgresql
  encoding: unicode
  username: vagrant
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: vngrs_development

test:
  <<: *default
  database: vngrs_test
  pool: 100

# production:
#   adapter: postgresql
#   database: db/production.postgresql
#   pool: 5
#   timeout: 5000
